### ISSUE TITLE
Release to Galaxy? 

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/hetzner.hcloud#10]
Hi, 
Do you know what's left before we can get
A) a pre-release to Galaxy 
B) a final release for Ansible 2.10?

If it's useful, I can add a Zuul-CI job which will do the build and publish to Galaxy

**Comment by LKaemmerling** [comment]
Hey @gundalow ,

we plan to add support for our Load Balancers and make several other small improvements before we wanted to make the release to Galaxy.

The support for Load Balancers will take place this week (we are more or less ready with the modules) and the plan was to release the collection after this.

Because of the CI, sure this could help, does it work directly on a tag? So we just tag (and make the release + release notes within Github) ?

**Comment by gundalow** [comment]
That's great news.

You are correct, Zuul will watch for a `git tag` +, so when you tag as `x.y.z` it will build and publish to Galaxy

Which version of Ansible will you be supporting with this collection? I see CI is currently running against the `devel` branch. We can (and likely should) update that to run against stable-2.10 *and* devel. I can raise a PR to do that. Are you supporting Ansible 2.9 either way the minimum version should be recorded in Galaxy.yml

**Comment by LKaemmerling** [comment]
We plan to support Ansible 2.9+. Actually, the whole process on what we need to do for the collection is a bit unclear for us, so it would be great if you could help us with that. I currently try within https://github.com/ansible-collections/hetzner.hcloud/pull/9 to cleanup a bit (remove the old facts modules and try fixing the sanity tests).

**Comment by felixfontein** [comment]
In case you remove the facts modules, you need to tombstone them (either here or in ansible-base). Otherwise users which still use them will get strange errors.

**Comment by gundalow** [comment]
@LKaemmerling I've created https://galaxy.ansible.com/hetzner and given you and Zuul powers on that.
You may wish to edit the description, add a logo etc via https://galaxy.ansible.com/my-content/namespaces/22631
Once https://github.com/ansible/project-config/pull/527 has been merged Zuul will do the build and upload when you push a tag to GitHub, you can test this with a `0.1.1` tag once 527 has been merged

**Comment by gundalow** [comment]
@LKaemmerling do you have any specific questions?

A lot of the policy (versioning, deprecation) is being documented in https://github.com/ansible-collections/overview/issues/45 it might be with spending some time to review that. Please do shout out with any questions.

**Comment by LKaemmerling** [comment]
We just released the first build to Ansible Galaxy
