### ISSUE TITLE
Inventory plugin adds undocumented variables 

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible-collections/hetzner.hcloud#116]
##### SUMMARY

When hosts are added via the inventory plugin, they have all kinds of variables set that were discovered by the plugin depending on which parameters are used. This is not documented.

`HINT: Did you know the documentation has an "Edit on GitHub" link on every page`

HINT: It doesn't, it doesn't even link to this repo here: https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_inventory.html

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

hetzner.hcloud.hcloud inventory plugin version 1.6.0

##### ACTUAL ISSUE

https://github.com/ansible-collections/hetzner.hcloud/blob/51865c29ab306b60be88963e81687761260eae4b/plugins/inventory/hcloud.py#L182 adds all kinds of variables (not semi-namespaced to e.g. `hcloud_*`) to hosts. These can be easily overwritten by accident, their names can't be changed and it is hard to know where these even come from due to their ambiguous naming conventions. Also error messages can end up in there (`"server_type": "No server type name found."` instead of just not setting this...).

Please document the ansible facts that this plugin sets and also consider renaming them. Also e.g. https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_info_module.html lists quite a lot more facts that you can discover about a server - maybe adding these to the inventory plugin makes sense too?

**Comment by MarkusTeufelberger** [comment]
@LKaemmerling - would PRs in this area be welcome? Currently this project seems a bit neglected, but I might be able to get it back into shape (fixing CI, addings Docs, adding a few features I need) relatively easily to iron out a few kinks I came across.

**Comment by MarkusTeufelberger** [comment]
Uhm... it can be closed of course, but the issue kinda won't go away automatically. It will just linger and lead to duplicate tickets/issues.

**Comment by jooola** [comment]
> When hosts are added via the inventory plugin, they have all kinds of variables set that were discovered by the plugin depending on which parameters are used. This is not documented.

I've been looking around, but didn't find any obvious way to document the host vars provided by the inventory plugin. Do you have examples where such host vars are documented?

> Also error messages can end up in there ("server_type": "No server type name found." instead of just not setting this...).

This has been solved in v2.

> adds all kinds of variables (not semi-namespaced to e.g. hcloud_*) to hosts. These can be easily overwritten by accident, their names can't be changed and it is hard to know where these even come from due to their ambiguous naming conventions.

This would be a big breaking change, we could introduce an option to add a prefix to the host vars.

> Also e.g. https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_info_module.html lists quite a lot more facts that you can discover about a server - maybe adding these to the inventory plugin makes sense too?

I don't think it makes sens to put all details related to a server in its host vars. If some essential variables are missing, I am happy to add them, but I'd prefer not to add everything by default.
