### ISSUE TITLE
Inventory: unexpected keyword argument 'id'

### ISSUE THREAD

**Issue by arosenhagen** [ansible-collections/hetzner.hcloud#130]
##### SUMMARY

Cannot read inventory
`ansible-inventory -i ./inventory/hcloud.yml --list`
 from hcloud with error
`Failed to parse inventory/hcloud.yml with ansible_collections.hetzner.hcloud.plugins.inventory.hcloud plugin: __init__() got an unexpected keyword argument 'id'`

Unfortunately this fails only with one specific hetzner-project. Maybe there's an issue on hetzners side?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hetzner.hcloud inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  python version = 3.9.12 (main, Mar 26 2022, 15:51:15) [Clang 13.1.6 (clang-1316.0.21.2)]
```

##### COLLECTION VERSION
```paste below
hetzner.hcloud 1.6.0
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING = True
DEFAULT_HOST_LIST = ['ansible/inventory']
DEPRECATION_WARNINGS = False
HOST_KEY_CHECKING = False
INVENTORY_ENABLED = ['hetzner.hcloud.hcloud']
```
```
# inventory/hcloud.yml
---
plugin: hetzner.hcloud.hcloud
token: "<SECRET>"
```

##### OS / ENVIRONMENT
macOS Monterey 12.3.1 (21E258)

##### ACTUAL RESULTS
```paste below
[WARNING]:  * Failed to parse inventory/hcloud.yml with ansible_collections.hetzner.hcloud.plugins.inventory.hcloud plugin: __init__() got an unexpected keyword argument 'id'
[WARNING]: Unable to parse inventory/hcloud.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

**Comment by LKaemmerling** [comment]
Hey @arosenhagen,

please update your underlying hcloud-python version to the last release (v1.16.0) (`pip install hcloud`). You use a pretty old hcloud python version as this was fixed there in August 2021 (https://github.com/hetznercloud/hcloud-python/releases/tag/v1.14.1)
