### ISSUE TITLE
hcloud_network_info does not always return delete_protection value

### ISSUE THREAD

**Issue by fin-ger** [ansible-collections/hetzner.hcloud#146]
##### SUMMARY

The documentation on `hcloud_network_info` claims that `hcloud_network_info.delete_protection` is always returned, but it is not. I have not set delete protection for a network, and the entry is missing from the result.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

hcloud_network_info

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/finchristensen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
```

**Comment by LKaemmerling** [comment]
Hey @fin-ger,

sorry for the late reply. I'm not able to reproduce it, in my tests the delete_protections is always returned. Do you still encounter this issue? If so feel free to reopen this issue or create a new one.
