### ISSUE TITLE
Publish 1.9.0 to Ansible Galaxy

### ISSUE THREAD

**Issue by Galaxy102** [ansible-collections/hetzner.hcloud#171]
Hello,

apparently something went wrong when releasing 1.9.0 as the new version hasn't made it yet to Ansible Galaxy, even if the docs state that this should happen automatically when creating the tag.

Could you please look into that?

Best regards and thank you in advance!

**Comment by apricote** [comment]
I am sorry, this was my first release of our ansible collection and I am not yet familiar with the process. 

It might be related to failures in our CI: https://dev.azure.com/ansible/hetzner.hcloud/_build?definitionId=35

@LKaemmerling is currently out of office, I will take a look at it with him once he is back.

**Comment by apricote** [comment]
The release pipeline in zuul was never triggered. I recreated the tag to re-run the webhook, and now the collection is publish on Ansible Galaxy. Thanks for reporting this @Galaxy102.

---

For posterity, I ran following commands as suggested by `felixfontain` on the `#ansible-community` Libera channel:

```
git tag --delete 1.9.0 ; git push upstream :1.9.0 ; git tag 1.9.0 ; git push upstream --tags
```
