### ISSUE TITLE
Inventory Plugin fails with "NoneType' object has no attribute 'items'"

### ISSUE THREAD

**Issue by apricote** [ansible-collections/hetzner.hcloud#179]
hetzner.hcloud                1.9.0
ansible [core 2.12.9]

```
[WARNING]: Ansible is being run in a world writable directory (PATH), ignoring it as an ansible.cfg source. For more
information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
[WARNING]:  * Failed to parse PATH/hcloud.yml with script plugin: problem running
PATH/hcloud.yml --list ([Errno 8] Exec format error: 'PATH/hcloud.yml')
[WARNING]:  * Failed to parse /hcloud.yml with auto plugin: 'NoneType' object has no attribute 'items'
[WARNING]:  * Failed to parse PATH/hcloud.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse PATH/hcloud.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not
allowed, this character is reserved to provide a port.
[WARNING]: Unable to parse PATH/hcloud.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

hcloud.yml
```
plugin: "hcloud"
token: "XXX"
````

_Originally posted by @maestroi in https://github.com/ansible-collections/hetzner.hcloud/issues/178#issuecomment-1379714476_

**Comment by apricote** [comment]
@maestroi Can you post the output of `ansible-inventory -i hcloud.yml -vvvvvv`?

**Comment by maestroi** [comment]
Yes here it is

`─ ansible-inventory -i hcloud.yml --list -e 'ansible_python_interpreter=/usr/bin/python3' -vvvv                                                                                       ─╯
ansible-inventory [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/maestro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/maestro/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-inventory
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml as it did not pass its verify_file() method
redirecting (type: inventory) ansible.builtin.hcloud to hetzner.hcloud.hcloud
Loading collection hetzner.hcloud from /home/maestro/.ansible/collections/ansible_collections/hetzner/hcloud
toml declined parsing /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml with script plugin: problem running
/mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml --list ([Errno 8] Exec format error: '/mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-
ansible/hcloud.yml')
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/script.py", line 150, in parse
    raise AnsibleParserError(to_native(e))
[WARNING]:  * Failed to parse /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml with auto plugin: 'NoneType' object has no attribute 'items'
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/home/maestro/.ansible/collections/ansible_collections/hetzner/hcloud/plugins/inventory/hcloud.py", line 278, in parse
    self._get_servers()
  File "/home/maestro/.ansible/collections/ansible_collections/hetzner/hcloud/plugins/inventory/hcloud.py", line 156, in _get_servers
    self.servers = self.client.servers.get_all()
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/servers/client.py", line 453, in get_all
    return super(ServersClient, self).get_all(
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/core/client.py", line 68, in get_all
    return self._get_all(
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/core/client.py", line 46, in _get_all
    page_result = list_function(
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/servers/client.py", line 436, in get_list
    ass_servers = [
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/servers/client.py", line 437, in <listcomp>
    BoundServer(self, server_data) for server_data in response["servers"]
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/servers/client.py", line 65, in __init__
    ipv6_network = IPv6Network.from_dict(public_net["ipv6"])
  File "/home/maestro/.local/lib/python3.8/site-packages/hcloud/core/domain.py", line 10, in from_dict
    supported_data = {k: v for k, v in data.items() if k in cls.__slots__}
[WARNING]:  * Failed to parse /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not
allowed, this character is reserved to provide a port.
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/ini.py", line 136, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /mnt/c/Users/super/OneDrive/Bureaublad/projects/acemining-ansible/hcloud.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}`

**Comment by apricote** [comment]
Thanks!

It looks like it crashes when passing `None` to `IPv6Network.from_dict()`, but we explicitly check if `public_net["ipv6"] is not None` and only execute `from_dict()` if it is set.

https://github.com/hetznercloud/hcloud-python/blob/5adcfb0a303d60b88abce837be3437f6f62b63c9/hcloud/servers/client.py#L78-L82

What version of `hcloud-python` are you using? You can find out from the file `/home/maestro/.local/lib/python3.8/site-packages/hcloud/__version__.py`

If you dont mind, could you send me the Project ID where this problem occurs to my email `julian.toelle <at> hetzner-cloud.de`. Then I can verify that everything is fine from the API side.

**Comment by maestroi** [comment]
Yes thank you! 
VERSION = "1.16.0"

**Comment by apricote** [comment]
I am going to close the issue. Please feel free to respond here or to create a new issue if you have any further problems, or if my suggestion from last week did not work.
