### ISSUE TITLE
Inventory load fails with server recreated from snapshot

### ISSUE THREAD

**Issue by PinkLolicorn** [ansible-collections/hetzner.hcloud#22]
##### SUMMARY
Plugin fails to read inventory with vm created from image. Most likely due to the fact that source snapshot was deleted.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hcloud

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.8/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### CONFIGURATION
No changes.

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
- Create VM on hetzner cloud
- Create snapshot of VM
- Remove VM
- Recreate VM from snapshot
- Remove snapshot

##### EXPECTED RESULTS
Ansible loads inventory.

##### ACTUAL RESULTS
The image propery is None for that specific server and causes load fail.

```
[WARNING]:  * Failed to parse /some/path/hcloud.yml with hcloud plugin: 'NoneType' object has no attribute 'name'
  File "/home/user/.local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/user/.local/lib/python3.8/site-packages/ansible/plugins/inventory/hcloud.py", line 205, in parse
    self._set_server_attributes(server)
  File "/home/user/.local/lib/python3.8/site-packages/ansible/plugins/inventory/hcloud.py", line 171, in _set_server_attributes
    self.inventory.set_variable(server.name, "server_type", to_native(server.image.name))
```

**Comment by PinkLolicorn** [comment]
I investigated further and I'm not really sure why this module uses image property to read server_type while API returns server_type.name. While image property returned by API is null, this whole problem looks like  it was caused by some mistake:

Current readouts:
```
debian-10
debian-10
debian-10
debian-10
debian-10
debian-10
```

**Comment by LKaemmerling** [comment]
Please use the collection v0.1.0 (or better: v0.2.0). There it is fixed.

**Comment by PinkLolicorn** [comment]
Thanks, it works. But I still wonder, why there is no fallback to `server_type.name` in case image is not present?

https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/inventory/hcloud.py#L204-L207
