### ISSUE TITLE
Create snapshots and backups

### ISSUE THREAD

**Issue by KrisLowet** [ansible-collections/hetzner.hcloud#227]
##### SUMMARY
Adding the option to create snapshots and backups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[hcloud_server module](https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_server_module.html#ansible-collections-hetzner-hcloud-hcloud-server-module)

##### ADDITIONAL INFORMATION
Before installing software updates, I like to take a snapshot or a backup from the servers. It would be a great addition to be able to take snapshots or a backup with this module.

**Comment by jooola** [comment]
This is probably related to #85

**Comment by jooola** [comment]
Closing this as duplicate of #85
