### ISSUE TITLE
Would it be possible to expose private networks to server facts and inventory plugin?

### ISSUE THREAD

**Issue by silviuvulcan** [ansible-collections/hetzner.hcloud#33]
##### SUMMARY

For my workflow it would be very useful to have the private network IPs exposed to the inventory plugin and/or server_facts. I know the hcloud cli already implements it (and I'm using it). Also having it as an option for `connect_with` would be icing on the cacke.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hcloud
hcloud_server_facts

##### ADDITIONAL INFORMATION

Most of my cloud instances are actually behind a gateway and I reach them over private networking / vpn links. I know I can get away with connect_with and split dns but still having access to private IPs could be beneficial. 

```yaml

```

**Comment by LKaemmerling** [comment]
Within the inventory this is already possible. You just need to specify the network: https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/inventory/hcloud.py#L61  and maybe change the connect_with value: https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/inventory/hcloud.py#L40

**Comment by LKaemmerling** [comment]
@silviuvulcan I guess this issue can be closed. If you encounter any other problems, feel free to reopen this issue or create a new one.
