### ISSUE TITLE
How to use multiple projects?

### ISSUE THREAD

**Issue by xoxys** [ansible-collections/hetzner.hcloud#39]
##### SUMMARY
How to use the dynamic inventory for multiple projects? The only way seems to be to have multiple inventory files and add the token to every inventory file. But this makes it hard to add these inventory files into e.g. a git repo.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
inventory/hcloud

**Comment by LKaemmerling** [comment]
This is not possible without copying the file (or using env variables). Ansible (or better said the API Token used for Ansible) lives in only one project, this is the highest entity. A project can have other entities. 

One thing you could do, would be symlinking your inventory file and then using a dedicated environment variable for each of your projects. You just need to set `HCLOUD_TOKEN` with the correct token.

**Comment by xoxys** [comment]
Lets say I have an inventory folder `inventories/` containing:

- static.ini
- aws.yml
- hcloud_project1.yml
- hcloud_project2.yml

I would like to use these inventories for a single play or to create a single inventory using `ansible-inventory -i inventories/ --list`. I can't find a way to make it work without adding a project token to the inventory file as `token:` parameter.  As there can only be one `HCLOUD_TOKEN` env var set while executing an Ansible command this will also not work. Would it be possible to allow to set a custom env variable name for the token in the inventory? E.g.

```
plugin: hcloud
token_env: HCLOUD_TOKEN_PROJECT1
```

This way users could use easily multiple projects without adding the required token statically to the inventory file.

**Comment by LKaemmerling** [comment]
Yeah with that folder structure you are currently bound to "hardcoding" the token. Using a field "token_env" or something like that looks interesting for me. Would you like to try to implement it :)?

**Comment by LKaemmerling** [comment]
Hey @xoxys,

do you try to implement it (or are you already working on a solution) :)? Otherwise, i would like to take it within this week and have this within the next collection release, which is expected to be at the end of the week.

**Comment by xoxys** [comment]
@LKaemmerling :wave: sorry was a bit busy with other tasks. Here you go, let me know what you think.

**Comment by LKaemmerling** [comment]
Thank you, i just merged your MR. Great work @xoxys! It will be included in the next release :)
