### ISSUE TITLE
hcloud dynamic inventory broken: 'NoneType' object has no attribute 'name'/hcloud declined parsing

### ISSUE THREAD

**Issue by bauerd** [ansible-collections/hetzner.hcloud#4]
##### SUMMARY
The [Hetzner Cloud dynamic inventory](https://docs.ansible.com/ansible/latest/plugins/inventory/hcloud.html) does not function anymore for me: `'NoneType' object has no attribute 'name'`/`hcloud declined parsing hcloud.yml as it did not pass its verify_file() method`

Used to work just fine and broke both within a CI pipeline and locally.

https://github.com/ansible/ansible/issues/69533 sent me here

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Hetzner Cloud (hcloud) dynamic inventory

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg
  configured module search path = [u'/home/runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/runner/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

ansible==2.9.2
hcloud==1.6.3

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
ANSIBLE_SSH_RETRIES(/home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg) = [u'/home/runner/work/kubernetes/kubernetes/ansible/hcloud.yml']
HOST_KEY_CHECKING(/home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg) = [u'hcloud']
```

##### OS / ENVIRONMENT
Ceased to function both on a hosted ubuntu-latest GitHub Actions workflow and locally on OS X 10.14.6. The `HCLOUD_TOKEN` environment variable is set and contains a valid API token.

##### STEPS TO REPRODUCE
hcloud.yml:
```
plugin: hcloud
groups:
  masters: labels.master is defined
  workers: labels.worker is defined
```

ansible.cfg:

```
[defaults]
host_key_checking = False
inventory = hcloud.yml

[ssh_connection]
retries=10
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null

[inventory]
enable_plugins = hcloud
```

##### EXPECTED RESULTS
Inventory discovers Hetzner Cloud hosts

##### ACTUAL RESULTS
Inventory does not discover Hetzner Cloud hosts

```
```yaml
ansible-inventory -vvv -i hcloud.yml --list
  env:
    GITHUB_TOKEN: ***
    DEPLOYMENT_SSH_PRIVATE_KEY_BASE64: ***
    HCLOUD_TOKEN: ***
    ANSIBLE_CONFIG: ansible/ansible.cfg
ansible-inventory 2.9.2
  config file = /home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg
  configured module search path = [u'/home/runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/runner/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /home/runner/work/kubernetes/kubernetes/ansible/ansible.cfg as config file
Skipping due to inventory source not existing or not being readable by the current user
hcloud declined parsing /home/runner/work/kubernetes/kubernetes/hcloud.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /home/runner/work/kubernetes/kubernetes/hcloud.yml
as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
```

**Comment by ssauriera** [comment]
Same issue, do you have any update?

**Comment by ssauriera** [comment]
After some checking i found that is working with this configuration:

> plugin: hcloud
> token: 
> locations:
>           - nbg1
> types:
>           - cx11

When I change any parameter this dosen't work

**Comment by ssauriera** [comment]
Finally I found my problem.

My servers are from snapshot and in my file located in :

/usr/lib/python2.7/dist-packages/ansible/plugins/inventory/hcloud.py

I comment de following lines:
![image](https://user-images.githubusercontent.com/5089486/82644660-f8c10d80-9c11-11ea-847b-33ada2ea3a01.png)

**Comment by LKaemmerling** [comment]
This is already fixed in the master branch of the new collection (https://github.com/ansible-collections/hetzner.hcloud/blob/master/plugins/inventory/hcloud.py). You could try to use this instead of the ansible build in, as this was planned to be released with Ansible 2.10. As Ansible 2.10 will no longer contain the "non-core" modules we have the new place here. We plan to publish the first stable version of the collection in the next few weeks.

@ssauriera could you test if the file I linked above fixes your issue?

**Comment by ssauriera** [comment]
@LKaemmerling changing the file you propose makes the inventory faild again. I'm going to work with the old one.

**Comment by LKaemmerling** [comment]
@ssauriera you could now use the released version fo this collection where the bug was fixed. I will close the issue as the bug itself is fixed.

**Comment by ktomk** [comment]
just a little bit of feedback from a users perspective: this was biting me yesterday at a not so good time.

no complaints: can confirm that removing ansible, installing it at 2.10.x (`ansible-base` on ubuntu), then installing hcloud-python via pip on python3 (`python3 -m pip install hcloud`) and getting `hetzner.hcloud` from galaxy (`ansible-galaxy collection install hetzner.hcloud`) did the job for me, the error went away.

Also I've found out that [`hcloud` CLI](https://github.com/hetznercloud/cli) is a good and stable intermediate fall-back if all things go down (it might be good you have in path already when trouble-shooting).

If I may suggest, if the [hetzner account on ansible galaxy website](https://galaxy.ansible.com/hetzner) would show the hetzner logo in the profile picture this would have given me a better impression (not your fault that with ansible galaxy it's not possible to re-install (remove + install) (at least on previous versions, there is a feature request for that)).

**Comment by LKaemmerling** [comment]
@ktomk thank you for your feedback! 

> If I may suggest, if the [hetzner account on ansible galaxy website](https://galaxy.ansible.com/hetzner) would show the hetzner logo in the profile picture this would have given me a better impression (not your fault that with ansible galaxy it's not possible to re-install (remove + install) (at least on previous versions, there is a feature request for that)).

I added the Hetzner Logo to Galaxy, good idea, thank you!
