### ISSUE TITLE
Broken Python 2.7 support

### ISSUE THREAD

**Issue by xoxys** [ansible-collections/hetzner.hcloud#44]
##### SUMMARY
Introduced `super()` calls in https://github.com/ansible-collections/hetzner.hcloud/pull/41 breaks python 2.7 compatibility... I know python 2.7 is EOL but for CentOS 7 you are still have to use python 2.7 as it is the system default and OS level dependency for e.g. yum.

The main issue is that zero-argument `super()`  calls were introduced in python 3. To fix it, we just need to add `super(InventoryModule, self)` as this is compatible for python2/3.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
inventory/hcloud.py

**Comment by xoxys** [comment]
@LKaemmerling would it be possible to tag a v1.2.1 release?

**Comment by LKaemmerling** [comment]
@xoxys i just released https://github.com/ansible-collections/hetzner.hcloud/releases/tag/1.2.1 it might take a bit to be available
