### ISSUE TITLE
Use resource action endpoints instead of global one

### ISSUE THREAD

**Issue by tomsiewert** [ansible-collections/hetzner.hcloud#498]
##### SUMMARY

In July 2023 the `/v1/actions` endpoint has been deprecated. Although it has been announced that it will not be available by the beginning of October 2023 it is still available. The customers were encouraged to migrate to the resource-specific action endpoints, but the Ansible collection does not do this yet (e.g. Volume creation). 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- Volume
- Server

**Comment by jooola** [comment]
Only some features of the `/v1/actions` endpoints were deprecated. Fetching multiple actions by their ID is still supported and required for the integrations to works.
