### ISSUE TITLE
Document installation process.

### ISSUE THREAD

**Issue by Andor** [ansible-collections/hetzner.hcloud#5]
##### SUMMARY
I tried to use this collection but unfortunately I got no luck since ansible 2.9 has no support for collections from git, only from galaxy or tarball.
It would be nice if you will either document how to install this collection with ansible-2.9 and made at least one release to galaxy.

I get errors like this:
```
ERROR! couldn't resolve module/action 'hcloud_floating_ip'. This often indicates a misspelling, missing collection, or incorrect module path.
```
or this:
```
fatal: [hostname]: FAILED! => {"msg": "Could not find imported module support code for hcloud_floating_ip.  Looked for either Hcloud.py or hcloud.py
```

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/andor/work/ansible/ansible.cfg
  configured module search path = ['/home/andor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```

**Comment by LKaemmerling** [comment]
The collection is not officially released yet, so it is currently not possible to install them through galaxy. The latest real release version is the build in ansible 2.9 release. We plan to release the collection in the near future, there are just a few things we need to do before we release it.

**Comment by Andor** [comment]
@LKaemmerling Sure 2.9 has most of hcloud-related modules, but it has no `hcloud_floating_ip` module which I really want to use.
I made some workarounds to use it already tho.
