### ISSUE TITLE
List allready created Servers

### ISSUE THREAD

**Issue by b-reich** [ansible-collections/hetzner.hcloud#50]
##### SUMMARY
There should be an option to list allready created servers. After getting a List of ServerNames or IDs someone could use this for deleting servers.
Its allready supportet by the hcloud-cli `hcloud server list`

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
In my example I try to make an rolling upgrade with new IPs:

https://gist.github.com/b-reich/29bebb78e8b9543505b2718ef7112111#file-hetzner_multiple-yml

**Comment by LKaemmerling** [comment]
Hey @b-reich,

you should be able to get all servers with the `hcloud_server_info` module:


```
- name: Get all servers
  hetzner.hcloud. hcloud_server_info:
  register: servers
- debug:
    msg: "{{ item.hcloud_server.ipv4_address }}"
  loop: "{{ servers.hcloud_server_info }}"

**Comment by b-reich** [comment]
@LKaemmerling thanks
