### ISSUE TITLE
Change the default 'master' branch to 'main' (rename)

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/hetzner.hcloud#60]
##### SUMMARY
Change the default 'master' branch to 'main' (rename)
https://github.com/ansible-collections/overview/issues/83
https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst

##### ISSUE TYPE
- Collection maintenance

**Comment by LKaemmerling** [comment]
Fixed with #67

**Comment by Andersson007** [comment]
@LKaemmerling thanks!
