### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by thijsj** [ansible-collections/hetzner.hcloud#65]
##### SUMMARY
Link to docs is not working, seems gone?

##### ISSUE TYPE
- Documentation Report

On the page https://galaxy.ansible.com/hetzner/hcloud
There is a link to the documentation: https://github.com/ansible-collections/hetzner.hcloud/tree/master/docs
This doesn't work. Has it been removed? Replaced?

**Comment by LKaemmerling** [comment]
Hey @thijsj,

please use `ansible-doc hetzner.hcloud.hcloud_server` on your local machine to see the documentation or otherwise, you can find the docs here: https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/

**Comment by thijsj** [comment]
Thanks for pointing me to the right documentation. But why not fix the link on the galaxy.ansible.com page?

**Comment by LKaemmerling** [comment]
@thijsj i just committed the change: 515a6d1
