### ISSUE TITLE
Default MASTER branch should be converted to MAIN branch

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/hetzner.hcloud#67]
##### SUMMARY
According to the [collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#branch-name-and-configuration),
default branches of the existing repositories under `ansible_collections` SHOULD be converted to use main.

**Comment by LKaemmerling** [comment]
Hey @Andersson007,

i just renamed the `main` branch.
