### ISSUE TITLE
hcloud volume detach 

### ISSUE THREAD

**Issue by leonorpw** [ansible-collections/hetzner.hcloud#84]
##### SUMMARY

Currently there is no way to deatch a volume from a server. Only via API Call https://docs.hetzner.cloud/#volume-actions-detach-volume

##### COMPONENT NAME

hcloud_volume

##### ADDITIONAL INFORMATION

I found this line "Create, update and attach/**detach** block volumes on the Hetzner Cloud." here [hetzner.hcloud.hcloud_volume – Create and manage block Volume on the Hetzner Cloud.](https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_volume_module.html#ansible-collections-hetzner-hcloud-hcloud-volume-module) but there is no option to deatch the volume.

Also the Example block got a Duplicated entry : Mount a existing Volume and automount

**Comment by LKaemmerling** [comment]
Hey @leonorpw,

sorry for the late answer. You can detach a volume from a server by simply removing the `server` option from your configuration. Here is a sample within our test suite: https://github.com/ansible-collections/hetzner.hcloud/blob/main/tests/integration/targets/hcloud_volume/tasks/main.yml#L113

**Comment by decentral1se** [comment]
I think this may be where all my confusion is coming from on https://github.com/ansible-collections/hetzner.hcloud/issues/47. Detaching a volume by dropping a key and having the state set to present doesn't really make it clear that you are detaching? That looks more like creation?

**Comment by decentral1se** [comment]
And actually, this doesn't work for me either? I am using the following tasks:

```diff
+    - name: Detach volume(s)
+      hcloud_volume:
+        name: "{{ item.volumes.name | default(item.instance) }}"
+        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
+      register: volumes
+      with_items: "{{ instance_conf }}"
+      async: 7200
+      poll: 0
+
+    - name: Wait for volume(s) detachment to complete
+      async_status:
+        jid: "{{ item.ansible_job_id }}"
+      register: hetzner_volumes
+      until: hetzner_volumes.finished
+      retries: 300
+      when: volumes.changed
+      with_items: "{{ volumes.results }}"
```

I get the following error:

> TASK [Wait for volume(s) detachment to complete] *******************************
> FAILED - RETRYING: Wait for volume(s) detachment to complete (300 retries left).
> failed: [localhost] (item={'started': 1, 'finished': 0, 'ansible_job_id': '203224931938.17488', 'results_file': '/home/decentral1se/.ansible_async/203224931938.17488', 'changed': True, 'failed': False, 'item': {'address': '95.216.167.92', 'identity_file': '/home/decentral1se/.cache/molecule/integration/default/ssh_key', 'instance': 'molecule-hetznercloud-06f68d40e4', 'port': 22, 'ssh_key_name': 'molecule-generated-58ba92b1-609f-5507-b486-3c9bf5302ba4', 'user': 'root', 'volumes': [{'name': 'molecule-hetznercloud-volume-1-06f68d40e4'}]}, 'ansible_loop_var': 'item'}) => {"ansible_job_id": "203224931938.17488", "ansible_loop_var": "item", "attempts": 2, "changed": false, "finished": 1, "item": {"ansible_job_id": "203224931938.17488", "ansible_loop_var": "item", "changed": true, "failed": false, "finished": 0, "item": {"address": "95.216.167.92", "identity_file": "/home/decentral1se/.cache/molecule/integration/default/ssh_key", "instance": "molecule-hetznercloud-06f68d40e4", "port": 22, "ssh_key_name": "molecule-generated-58ba92b1-609f-5507-b486-3c9bf5302ba4", "user": "root", "volumes": [{"name": "molecule-hetznercloud-volume-1-06f68d40e4"}]}, "results_file": "/home/decentral1se/.ansible_async/203224931938.17488", "started": 1}, "msg": "missing required arguments: size"}

**Comment by LKaemmerling** [comment]
> And actually, this doesn't work for me either? I am using the following tasks:
> 
> ```diff
> +    - name: Detach volume(s)
> +      hcloud_volume:
> +        name: "{{ item.volumes.name | default(item.instance) }}"
> +        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
> +      register: volumes
> +      with_items: "{{ instance_conf }}"
> +      async: 7200
> +      poll: 0
> +
> +    - name: Wait for volume(s) detachment to complete
> +      async_status:
> +        jid: "{{ item.ansible_job_id }}"
> +      register: hetzner_volumes
> +      until: hetzner_volumes.finished
> +      retries: 300
> +      when: volumes.changed
> +      with_items: "{{ volumes.results }}"
> ```
> 
> I get the following error:
> 
> > TASK [Wait for volume(s) detachment to complete] *******************************
> > FAILED - RETRYING: Wait for volume(s) detachment to complete (300 retries left).
> > failed: [localhost] (item={'started': 1, 'finished': 0, 'ansible_job_id': '203224931938.17488', 'results_file': '/home/decentral1se/.ansible_async/203224931938.17488', 'changed': True, 'failed': False, 'item': {'address': '95.216.167.92', 'identity_file': '/home/decentral1se/.cache/molecule/integration/default/ssh_key', 'instance': 'molecule-hetznercloud-06f68d40e4', 'port': 22, 'ssh_key_name': 'molecule-generated-58ba92b1-609f-5507-b486-3c9bf5302ba4', 'user': 'root', 'volumes': [{'name': 'molecule-hetznercloud-volume-1-06f68d40e4'}]}, 'ansible_loop_var': 'item'}) => {"ansible_job_id": "203224931938.17488", "ansible_loop_var": "item", "attempts": 2, "changed": false, "finished": 1, "item": {"ansible_job_id": "203224931938.17488", "ansible_loop_var": "item", "changed": true, "failed": false, "finished": 0, "item": {"address": "95.216.167.92", "identity_file": "/home/decentral1se/.cache/molecule/integration/default/ssh_key", "instance": "molecule-hetznercloud-06f68d40e4", "port": 22, "ssh_key_name": "molecule-generated-58ba92b1-609f-5507-b486-3c9bf5302ba4", "user": "root", "volumes": [{"name": "molecule-hetznercloud-volume-1-06f68d40e4"}]}, "results_file": "/home/decentral1se/.ansible_async/203224931938.17488", "started": 1}, "msg": "missing required arguments: size"}

Hey @decentral1se,

I looked at the code and it looks like the name you specified was not existing, and that is why it required the size.  As you can see within the tests, the function for detaching works perfectly: https://github.com/ansible-collections/hetzner.hcloud/blob/main/tests/integration/targets/hcloud_volume/tasks/main.yml#L113

Therefore I would recommend you check your variables. It looks like the name is not passed correctly.
