### ISSUE TITLE
Inventory plugin does not work with full qualified name

### ISSUE THREAD

**Issue by xoxys** [ansible-collections/hetzner.hcloud#86]
##### SUMMARY
After upgrading to Ansible 4.0.0/ansible-base 2.11.0 the inventory plugin does not work with the full qualified name anymore:

```
---
plugin: hetzner.hcloud.hcloud
keyed_groups:
  - key: labels.os
    separator: ""
```

results in 

```
[WARNING]:  * Failed to parse ./inventory/hcloud.yml with auto plugin: Invalid value "hetzner.hcloud.hcloud" for configuration option "plugin_type: inventory plugin:
ansible_collections.hetzner.hcloud.plugins.inventory.hcloud setting: plugin ", valid values are: ['hcloud']
```

The quick fix is to use `plugin: hcloud` in the inventory file, but it might be confusing while the Ansible docs recommend using the full qualified name for plugins coming from a collection https://docs.ansible.com/ansible/latest/plugins/inventory.html#using-inventory-plugins. I guess it's related to https://github.com/ansible-collections/hetzner.hcloud/blob/main/plugins/inventory/hcloud.py#L26 and some kind of stricter validation in Ansible 4.0.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
inventory hcloud

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1] 
  config file = /home/ansibleremote/ansible-dc/ansible.cfg
  configured module search path = ['/home/ansibleremote/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python38/ansible/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/ansibleremote/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/python38/ansible/bin/ansible
  python version = 3.8.6 (default, Oct 27 2020, 09:13:12) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.0.1
  libyaml = True
```

**Comment by xoxys** [comment]
Maybe using `choices: ["hcloud", "hetzner.hcloud.hcloud"]` would work to fix the compatibility issue. Still not sure where to go, but I can prepare a PR if you would like to add it.

**Comment by LKaemmerling** [comment]
Hey @xoxys,

thank you for your report :) I have created an MR to fix this issue. I guess it was overseen when migrating to the collection :)

**Comment by xoxys** [comment]
Thanks for the fix :)
