### ISSUE TITLE
Firewall: Creation of "out" rules not possible

### ISSUE THREAD

**Issue by agnf** [ansible-collections/hetzner.hcloud#88]
##### SUMMARY

When you try to create a firewall with "out" rules you end up with an error message. This is (as far as I can tell) due to the way destination_ips and source_ips are handled in hcloud_firewall.py

```python
    @staticmethod
    def define_module():
        return AnsibleModule(
            argument_spec=dict(
                id={"type": "int"},
                name={"type": "str"},
                rules=dict(
                    type="list",
                    elements="dict",
                    options=dict(
                        direction={"type": "str", "choices": ["in", "out"]},
                        protocol={"type": "str", "choices": ["icmp", "udp", "tcp"]},
                        port={"type": "str"},
                        source_ips={"type": "list", "elements": "str"},
                        destination_ips={"type": "list", "elements": "str", "default": []},
                    ),
                    required_together=[["direction", "port", "protocol", "source_ips"]]
                ),
                labels={"type": "dict"},
                state={
                    "choices": ["absent", "present"],
                    "default": "present",
                },
                **Hcloud.base_module_arguments()
            ),
            required_one_of=[['id', 'name']],
            required_if=[['state', 'present', ['name']]],
            supports_check_mode=True,
        )
```
While for destination_ips a default is given, this is not true for source_ips. When a rule with just destination_ips is created, the process fails because source_ips as no value. 

If a default value is also given for source_ips then the required-together line is most likely less effective as at least source_ips will always have a value.

Removing the default values and changing the required part to 
```python
                    required_together=[["direction", "port", "protocol"]],
                    required_if=[['direction', 'out', ['destination_ips']], ['direction', 'in', ['source_ips']]]
```
did work to some extend for me, however then the process stops at another place when one of the other is empty (see  _prepare_result_rule(self, rule) and _create_firewall(self)

Unfortunately, my Python skill are not good enough to provide a good fix and PR...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_firewall.py

**Comment by LKaemmerling** [comment]
Hey @agnf,

thank you for your report! I have created an MR to address your issues. This one will be included in the next release.
