### ISSUE TITLE
 hcloud_volume_info instead of hcloud_volume_facts

### ISSUE THREAD

**Issue by rightaway** [ansible-collections/hetzner.hcloud#92]
`hcloud_volume_info` shouldn't require `api_token` if it's already in the environment variable of the machine running ansible. That's how `hcloud_volume_facts` worked. There's no need to give this value again all of a sudden.

I'm getting `Failed to import the required Python library (hcloud-python) on staging's Python /usr/bin/python3` error as well when I'm running this. Why does `hcloud_volume_info` require pip `hcloud` to be installed (because `hcloud_volume_facts` didn't).

**Comment by LKaemmerling** [comment]
Hey @rightaway,

`hcloud_volume_facts` is just a symlink to `hcloud_volume_info`. There is no difference between those modules. Also all modules required the `hcloud` python SDK since the beginning (when they were build in ansible this was required too).

**Comment by rightaway** [comment]
I wasn't having to specify `api_token` or install pip `hcloud` before, can you think of anything that changed? Last time I used this was 2 years ago on terraform 0.12. Could the differences be explained by using `hcloud_volume_facts` from that long ago or still it would have required both these things back then?

**Comment by LKaemmerling** [comment]
@rightaway the Modules didn't changed a lot since then and it was always required to install the hcloud-python (pip install hcloud) and to set a token. 

What does Terraform have to do with the ansible modules? If you think about the Terraform datasource hcloud_volume, there you only Need to specify the token.

**Comment by rightaway** [comment]
I shouldn't have mentioned terraform it's not related. Not sure why hcloud_volume_facts worked for me before without the api_token or pip hcloud, possibly they were being provided in some other way but I don't know how.
