### ISSUE TITLE
Can't group by network

### ISSUE THREAD

**Issue by rightaway** [ansible-collections/hetzner.hcloud#93]
##### SUMMARY

There's no way to add network names to keyed_groups. This should be possible since it's valid to group by them like any other parameters.

Documentation should include all the possible values that can be set in keyed_groups. Can you tell me what values are possible to group by?

It would be good be able to group by subnet names, which the API doesn't allow. Is there a reason for this? It's good to have named subnets because you would put servers in a subnet based on a common grouping.

**Comment by LKaemmerling** [comment]
You can specify a network when defining the inventory. Multiple networks in one file are not possible, because the inventory needs to know from which network it should set the IP addresses in the inventory.
